name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint and syntax check
        run: |
          # Poderíamos usar uma rotina de análise sintática e estática

      - name: Run tests
        run: |
          # Poderíamos rodar os testes do projeto